# Generated by Django 5.2.14 on 2026-05-22 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PondFeedingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fed', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pond Feeding Log',
                'verbose_name_plural': 'Pond Feeding Logs',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('total_area', models.DecimalField(decimal_places=2, help_text='Total area in square meters', max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farm',
                'verbose_name_plural': 'Farms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('caretaker_name', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('size', models.DecimalField(decimal_places=2, help_text='Size in square meters', max_digits=10)),
                ('depth', models.DecimalField(decimal_places=2, help_text='Depth in meters', max_digits=5)),
                ('capacity', models.IntegerField(default=0, help_text='Maximum fish capacity')),
                ('product_name', models.CharField(blank=True, max_length=100)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('breeding_type', models.CharField(blank=True, help_text='e.g. Reproduction, Crilings', max_length=50)),
                ('male_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('female_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('shelf_position', models.CharField(blank=True, help_text='For Superworm Cabin, e.g. Left-1-1', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('empty', 'Empty'), ('harvesting', 'Harvesting')], default='empty', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponds', to='operations.farm')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_ponds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pond',
                'verbose_name_plural': 'Ponds',
                'ordering': ['farm', 'name'],
            },
        ),
    ]
