# Generated by Django 5.2.14 on 2026-05-22 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0002_initial'),
        ('operations', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pond',
            name='species',
            field=models.ManyToManyField(blank=True, related_name='ponds', to='stock.species'),
        ),
        migrations.AddField(
            model_name='pondfeedinglog',
            name='feed_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feed.feedtype'),
        ),
        migrations.AddField(
            model_name='pondfeedinglog',
            name='pond',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_logs', to='operations.pond'),
        ),
        migrations.AddField(
            model_name='pondfeedinglog',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
