# Generated by Django 5.2.14 on 2026-05-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pond',
            name='manager',
        ),
    ]
