# Generated by Django 4.2.30 on 2026-09-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_remove_pond_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='pond',
            name='last_sanitized_date',
            field=models.DateField(blank=True, help_text='Date when this pond or tank was last sanitized', null=True),
        ),
    ]
