# Generated by Django 4.2.30 on 2026-10-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_pond_last_sanitized_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pond',
            name='capacity_2',
            field=models.IntegerField(blank=True, default=0, help_text='Quantity for second product', null=True),
        ),
        migrations.AddField(
            model_name='pond',
            name='product_name_2',
            field=models.CharField(blank=True, help_text='Second product name for dual tracking (e.g. Crilings)', max_length=100),
        ),
    ]
