# Generated by Django 4.2.30 on 2026-10-05 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0005_pond_capacity_2_pond_product_name_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='PondTransferBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='Crilings', max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_batches', to='operations.pond')),
                ('source_pond', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transfers', to='operations.pond')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pond Transfer Batch',
                'verbose_name_plural': 'Pond Transfer Batches',
                'ordering': ['transfer_date', 'created_at'],
            },
        ),
    ]
