# Generated by Django 4.2.30 on 2026-10-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_pondtransferbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='pondfeedinglog',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
