# Generated by Django 4.2.30 on 2026-10-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_pondfeedinglog_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pondfeedinglog',
            name='quantity_grams',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount fed in grams', max_digits=10, null=True),
        ),
    ]
