# Generated by Django 6.0.5 on 2026-08-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_assigned_farm_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('customer', 'Customer'), ('rider', 'Rider')], default='customer', max_length=20),
        ),
    ]
