# Generated by Django 5.2.14 on 2026-05-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(help_text='Date when forecast was made')),
                ('predicted_harvest_date', models.DateField()),
                ('predicted_weight', models.DecimalField(decimal_places=2, help_text='Predicted average weight in grams', max_digits=8)),
                ('predicted_quantity', models.IntegerField()),
                ('predicted_total_yield', models.DecimalField(decimal_places=2, help_text='Predicted total yield in kg', max_digits=12)),
                ('confidence_level', models.DecimalField(decimal_places=2, help_text='Confidence percentage', max_digits=5)),
                ('algorithm_used', models.CharField(default='linear_regression', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Harvest Forecast',
                'verbose_name_plural': 'Harvest Forecasts',
                'ordering': ['-forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='SalesForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(help_text='Date when forecast was made')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('predicted_demand_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('predicted_revenue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('confidence_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('algorithm_used', models.CharField(default='moving_average', max_length=50)),
                ('actual_demand_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sales Forecast',
                'verbose_name_plural': 'Sales Forecasts',
                'ordering': ['-forecast_date'],
            },
        ),
    ]
