# Generated by Django 5.2.14 on 2026-05-22 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestforecast',
            name='stock_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_forecasts', to='stock.stockbatch'),
        ),
        migrations.AddField(
            model_name='salesforecast',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.species'),
        ),
    ]
