# Generated by Django 5.2.14 on 2026-05-22 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedinglog',
            name='stock_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_logs', to='stock.stockbatch'),
        ),
        migrations.AddField(
            model_name='feedinventory',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedstockmovement',
            name='feed_inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='feed.feedinventory'),
        ),
        migrations.AddField(
            model_name='feedstockmovement',
            name='feeding_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='feed.feedinglog'),
        ),
        migrations.AddField(
            model_name='feedstockmovement',
            name='moved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedstockmovement',
            name='feed_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='feed.feedtype'),
        ),
        migrations.AddField(
            model_name='feedinventory',
            name='feed_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='feed.feedtype'),
        ),
        migrations.AddField(
            model_name='feedinglog',
            name='feed_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feeding_logs', to='feed.feedtype'),
        ),
    ]
