# Generated by Django 4.2.30 on 2026-10-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_feedtype_managers_feedtype_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedtype',
            name='kg_per_sack',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Weight in kg per sack', max_digits=10),
        ),
        migrations.AddField(
            model_name='feedtype',
            name='quantity_sacks',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Number of sacks', max_digits=10),
        ),
        migrations.AlterField(
            model_name='feedtype',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
