# Generated by Django 4.2.30 on 2026-10-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_feedtype_kg_per_sack_feedtype_quantity_sacks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedtype',
            name='kg_per_sack',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Weight in kg per sack', max_digits=10),
        ),
    ]
