# Generated by Django 4.2.30 on 2026-10-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_alter_feedtype_kg_per_sack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedtype',
            name='quantity_sacks',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Number of sacks', max_digits=12),
        ),
    ]
