# Generated by Django 4.2.30 on 2026-10-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_alter_feedtype_quantity_sacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedstockmovement',
            name='delta_kg',
            field=models.DecimalField(decimal_places=4, help_text='Signed stock change in kg', max_digits=12),
        ),
    ]
