# Generated by Django 4.2.30 on 2026-10-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_alter_feedstockmovement_delta_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedtype',
            name='quantity_sacks',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Number of sacks', max_digits=14),
        ),
    ]
