# Generated by Django 4.2.30 on 2026-10-10 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_alter_feedtype_quantity_sacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedSack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sack_number', models.PositiveIntegerField(default=1, help_text='Sack sequential number (1, 2, ...)')),
                ('initial_weight_kg', models.DecimalField(decimal_places=3, default=50.0, help_text='Weight when added in kg', max_digits=10)),
                ('current_weight_kg', models.DecimalField(decimal_places=3, default=50.0, help_text='Current remaining weight in kg', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sacks', to='feed.feedtype')),
            ],
            options={
                'verbose_name': 'Feed Sack',
                'verbose_name_plural': 'Feed Sacks',
                'ordering': ['sack_number', 'created_at'],
            },
        ),
    ]
