# Generated by Django 4.2.30 on 2026-10-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_feedsack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedtype',
            name='protein_content',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Protein percentage', max_digits=5),
        ),
    ]
