# Generated by Django 5.2.14 on 2026-05-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField()),
                ('quantity_harvested', models.IntegerField()),
                ('total_weight_kg', models.DecimalField(decimal_places=2, help_text='Total weight in kg', max_digits=12)),
                ('average_weight_per_fish', models.DecimalField(decimal_places=2, help_text='Average weight in grams', max_digits=8)),
                ('grade_a_quantity', models.IntegerField(default=0, help_text='Premium grade fish count')),
                ('grade_b_quantity', models.IntegerField(default=0, help_text='Standard grade fish count')),
                ('grade_c_quantity', models.IntegerField(default=0, help_text='Below standard grade fish count')),
                ('is_partial_harvest', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Harvest Record',
                'verbose_name_plural': 'Harvest Records',
                'ordering': ['-harvest_date'],
            },
        ),
        migrations.CreateModel(
            name='HarvestSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('estimated_quantity', models.IntegerField(help_text='Estimated number of fish to harvest')),
                ('estimated_total_weight', models.DecimalField(decimal_places=2, help_text='Estimated total weight in kg', max_digits=12)),
                ('target_weight', models.DecimalField(decimal_places=2, help_text='Target weight per fish in grams', max_digits=8)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Harvest Schedule',
                'verbose_name_plural': 'Harvest Schedules',
                'ordering': ['scheduled_date'],
            },
        ),
    ]
