# Generated by Django 5.2.14 on 2026-05-22 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('harvest', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestrecord',
            name='stock_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_records', to='stock.stockbatch'),
        ),
        migrations.AddField(
            model_name='harvestrecord',
            name='harvested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='harvestschedule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='harvestschedule',
            name='stock_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_schedules', to='stock.stockbatch'),
        ),
        migrations.AddField(
            model_name='harvestrecord',
            name='harvest_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvest_records', to='harvest.harvestschedule'),
        ),
    ]
