# Generated by Django 5.2.14 on 2026-05-22 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0002_initial'),
        ('stock', '0002_remove_species_average_growth_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestrecord',
            name='stock_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_records', to='stock.stockbatch'),
        ),
        migrations.AlterField(
            model_name='harvestschedule',
            name='stock_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_schedules', to='stock.stockbatch'),
        ),
    ]
