# Generated by Django 6.0.3 on 2026-03-29 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(help_text='Date when forecast was made')),
                ('predicted_harvest_date', models.DateField()),
                ('predicted_weight', models.DecimalField(decimal_places=2, help_text='Predicted average weight in grams', max_digits=8)),
                ('predicted_quantity', models.IntegerField()),
                ('predicted_total_yield', models.DecimalField(decimal_places=2, help_text='Predicted total yield in kg', max_digits=12)),
                ('confidence_level', models.DecimalField(decimal_places=2, help_text='Confidence percentage', max_digits=5)),
                ('algorithm_used', models.CharField(default='linear_regression', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fish_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_forecasts', to='fish.fishbatch')),
            ],
            options={
                'verbose_name': 'Harvest Forecast',
                'verbose_name_plural': 'Harvest Forecasts',
                'ordering': ['-forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField()),
                ('metric_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('total_ponds_active', models.IntegerField(default=0)),
                ('total_fish_stock', models.IntegerField(default=0)),
                ('total_biomass_kg', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_feed_used_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('feed_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_mortality', models.IntegerField(default=0)),
                ('mortality_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_harvest_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('harvest_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_orders', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Performance Metric',
                'verbose_name_plural': 'Performance Metrics',
                'ordering': ['-metric_date'],
                'unique_together': {('metric_date', 'metric_type')},
            },
        ),
        migrations.CreateModel(
            name='SalesForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(help_text='Date when forecast was made')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('predicted_demand_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('predicted_revenue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('confidence_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('algorithm_used', models.CharField(default='moving_average', max_length=50)),
                ('actual_demand_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fish.species')),
            ],
            options={
                'verbose_name': 'Sales Forecast',
                'verbose_name_plural': 'Sales Forecasts',
                'ordering': ['-forecast_date'],
            },
        ),
    ]
