# Generated by Django 6.0.4 on 2026-08-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rider_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
