# Generated by Django 6.0.4 on 2026-08-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_product_price_per_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pieces_per_kg',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
