# Generated by Django 6.0.4 on 2026-08-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_product_pieces_per_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcash_name', models.CharField(default='SILAY SUPERWORM & CRAYFISH', max_length=150)),
                ('gcash_number', models.CharField(default='09171234567', max_length=30)),
                ('gcash_qr_image', models.ImageField(blank=True, null=True, upload_to='payment_qr/')),
                ('is_gcash_enabled', models.BooleanField(default=True)),
                ('is_cod_enabled', models.BooleanField(default=True)),
                ('paymongo_public_key', models.CharField(blank=True, max_length=150)),
                ('paymongo_secret_key', models.CharField(blank=True, max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Setting',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
    ]
