# Generated by Django 6.0.4 on 2026-09-03 06:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_paymentsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InputLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('user_role', models.CharField(default='Owner', max_length=50)),
                ('action', models.CharField(choices=[('added', 'Added Data'), ('deleted', 'Deleted Data'), ('updated', 'Updated Data')], default='added', max_length=20)),
                ('module', models.CharField(default='Sales Orders', max_length=100)),
                ('target_entity', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Input Log',
                'verbose_name_plural': 'Input Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
