# Generated by Django 6.0.4 on 2026-09-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_inputlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='proof_of_delivery',
            field=models.ImageField(blank=True, null=True, upload_to='proof_of_delivery/'),
        ),
    ]
