# Generated by Django 4.2.30 on 2026-09-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_delivery_proof_of_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rider',
            name='license_evidence',
            field=models.ImageField(blank=True, null=True, upload_to='rider_licenses/'),
        ),
    ]
