# Generated by Django 4.2.30 on 2026-09-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_rider_address_rider_license_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('pcs', 'Pieces (pcs)'), ('kg', 'Kilograms (kg)'), ('tub', 'Tubs'), ('pair', 'Pairs'), ('pack', 'Packs'), ('head', 'Heads')], default='pcs', help_text='Measurement unit for this product', max_length=20),
        ),
    ]
