# Generated by Django 4.2.30 on 2026-09-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_product_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inputlog',
            name='action',
            field=models.CharField(choices=[('added', 'Added Data'), ('deleted', 'Deleted Data'), ('updated', 'Updated Data'), ('create', 'Created Data')], default='added', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('harvest', 'Harvest Inflow'), ('sale', 'Sales Deduction'), ('adjustment', 'Manual Adjustment'), ('mortality', 'Mortality/Loss')], max_length=20),
        ),
    ]
