# Generated by Django 4.2.30 on 2026-09-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_delivery_current_latitude_delivery_current_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(blank=True, default='pcs', help_text='Measurement unit for this product', max_length=50),
        ),
    ]
