# Generated by Django 6.0.3 on 2026-03-29 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fish', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_date', models.DateField()),
                ('sample_size', models.IntegerField(help_text='Number of fish sampled')),
                ('average_weight', models.DecimalField(decimal_places=2, help_text='Average weight in grams', max_digits=8)),
                ('min_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('average_length', models.DecimalField(blank=True, decimal_places=2, help_text='Average length in cm', max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fish_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_samples', to='fish.fishbatch')),
                ('sampled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Growth Sample',
                'verbose_name_plural': 'Growth Samples',
                'ordering': ['-sample_date'],
            },
        ),
        migrations.CreateModel(
            name='MortalityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('quantity', models.IntegerField(help_text='Number of fish died')),
                ('cause', models.CharField(choices=[('disease', 'Disease'), ('water_quality', 'Poor Water Quality'), ('predation', 'Predation'), ('handling', 'Handling Stress'), ('unknown', 'Unknown'), ('other', 'Other')], default='unknown', max_length=20)),
                ('estimated_weight_loss', models.DecimalField(blank=True, decimal_places=2, help_text='Total weight lost in grams', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fish_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortality_records', to='fish.fishbatch')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mortality Record',
                'verbose_name_plural': 'Mortality Records',
                'ordering': ['-record_date'],
            },
        ),
    ]
