# Generated by Django 6.0.3 on 2026-03-29 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ponds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('average_growth_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Average growth rate in grams per day', max_digits=5, null=True)),
                ('optimal_temperature_min', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('optimal_temperature_max', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('optimal_ph_min', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('optimal_ph_max', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Species',
                'verbose_name_plural': 'Species',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FishBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=50, unique=True)),
                ('stocking_date', models.DateField()),
                ('initial_quantity', models.IntegerField()),
                ('current_quantity', models.IntegerField()),
                ('initial_average_weight', models.DecimalField(decimal_places=2, help_text='Initial weight in grams', max_digits=8)),
                ('current_average_weight', models.DecimalField(decimal_places=2, help_text='Current weight in grams', max_digits=8)),
                ('stage', models.CharField(choices=[('fry', 'Fry'), ('fingerling', 'Fingerling'), ('juvenile', 'Juvenile'), ('adult', 'Adult'), ('market_size', 'Market Size')], default='fry', max_length=20)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish_batches', to='ponds.pond')),
                ('stocked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='fish.species')),
            ],
            options={
                'verbose_name': 'Fish Batch',
                'verbose_name_plural': 'Fish Batches',
                'ordering': ['-stocking_date'],
            },
        ),
    ]
