# Generated by Django 5.2.14 on 2026-05-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='average_growth_rate',
        ),
    ]
