# Generated by Django 6.0.3 on 2026-03-29 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fish', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('starter', 'Starter Feed'), ('grower', 'Grower Feed'), ('finisher', 'Finisher Feed'), ('specialty', 'Specialty Feed')], max_length=20)),
                ('protein_content', models.DecimalField(decimal_places=2, help_text='Protein percentage', max_digits=5)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feed Type',
                'verbose_name_plural': 'Feed Types',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeedInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='feed.feedtype')),
            ],
            options={
                'verbose_name': 'Feed Inventory',
                'verbose_name_plural': 'Feed Inventories',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='FeedingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_kg', models.DecimalField(decimal_places=2, help_text='Amount fed in kg', max_digits=8)),
                ('feeding_time', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fish_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_logs', to='fish.fishbatch')),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feeding_logs', to='feed.feedtype')),
            ],
            options={
                'verbose_name': 'Feeding Log',
                'verbose_name_plural': 'Feeding Logs',
                'ordering': ['-feeding_time'],
            },
        ),
    ]
